---
title: "Project1_776"
author: "Ritesh Bachar"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

```{r setting up background}

## Installing the tidyverse package
if (!require("tidyverse", quietly = TRUE)) {
    install.packages("tidyverse")
}

library("tidyverse")

## Install the tidytuesdayR package if you don't have it
if (!require("tidytuesdayR", quietly = TRUE)) {
    install.packages("tidytuesdayR")
}

## Install the remotes package if you don't have it
if (!require("remotes", quietly = TRUE)) {
    install.packages("remotes")
}
## Install the tidytuesdayR package (from GitHub) if you don't have it
if (!require("tidytuesdayR", quietly = TRUE)) {
    remotes::install_github("dslc-io/tidytuesdayR")
}

##avioding re-downloading the data
library("here")
library("tidyverse")

# testing if a directory named "data" exists locally
if (!dir.exists(here("data"))) {
    dir.create(here("data"))
}

# saves data only once (not each time you knit a R Markdown)
if (!file.exists(here("data", "chocolate.RDS"))) {
    url_csv <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv"
    chocolate <- readr::read_csv(url_csv)

    # save the file to RDS objects
    saveRDS(chocolate, file = here("data", "chocolate.RDS"))
}

##reading the rds file locally
chocolate <- readRDS(here("data", "chocolate.RDS"))
as_tibble(chocolate)

##taking a glimpse at the data
glimpse(chocolate)

```

## Part 1- Exploring data

```{r part1 q1}
## 1. Make a histogram of the rating scores to visualize the overall distribution of scores. Change the number of bins from the default to 10, 15, 20, and 25. Pick on the one that you think looks the best. Explain what the difference is when you change the number of bins and explain why you picked the one you did.

library(ggplot2)

ggplot(chocolate, aes(x=rating))+
  geom_histogram()+
  ggtitle("Ratings with default bin")

ggplot(chocolate, aes(x=rating))+
  geom_histogram(binwidth = 10)+
  ggtitle("Ratings with bin 10")

ggplot(chocolate, aes(x=rating))+
  geom_histogram(binwidth = 15)+
  ggtitle("Ratings with bin 15")

ggplot(chocolate, aes(x=rating))+
  geom_histogram(binwidth = 20)+
  ggtitle("Ratings with bin 20")

ggplot(chocolate, aes(x=rating))+
  geom_histogram(binwidth = 25)+
  ggtitle("Ratings with bin 25")

```

#I think the default one looks best. The histogram with the default bins makes sense as the counts of the ratings can be observed whereas for the 10,15,20 and 25 values the chart area is just filled with a black box.

```{r part1 q2}
## 2. Consider the countries where the beans originated from. How many reviews come from each country of bean origin?
library(dplyr)
library(knitr)
review_from_country <- chocolate %>%
  group_by(country_of_bean_origin) %>%
  summarize(review = n())

# Printing the table using kable
kable(review_from_country, caption = "Table of Reviews by Country")
```

```{r part1 q3}
## 3. What is average rating scores from reviews of chocolate bars that have Ecuador as country_of_bean_origin in this dataset? For this same set of reviews, also calculate (1) the total number of reviews and (2) the standard deviation of the rating scores. Your answer should be a new data frame with these three summary statistics in three columns. Label the name of these columns mean, sd, and total.

q3_ecuador <- filter(chocolate, country_of_bean_origin == "Ecuador")

q3_df <- q3_ecuador%>%
  summarise(
 'mean' =  mean(rating),
 'sd' = sd(rating),
 'total' = n(),
)

print(q3_df)


```

```{r part1 q4}
## 4. Which company location makes the best chocolate (or has the highest ratings on average) with beans from Ecuador?

q4_df <- q3_ecuador%>%
  arrange(desc(rating))

best_rating <- filter(q4_df, rating == 4)                 #extracting from row
best_company <- select(best_rating, company_location)     #extracting from column
print(best_company)

```

```{r part1 q5}
## 5. Calculate the average rating across all country of origins for beans. Which top 3 countries (for bean origin) have the highest ratings on average?

bean_origin <- chocolate %>%
  select(country_of_bean_origin, rating)

average_ratings <- bean_origin %>%
  group_by(country_of_bean_origin) %>%
  summarise(avg_rating = mean(rating))

average_ratings_descending <- average_ratings%>%
  arrange(desc(avg_rating))

top_rating <- filter(average_ratings_descending, avg_rating >= 3.5)                 #extracting from row
top_country <- select(top_rating, country_of_bean_origin)     #extracting from column
print(top_country)

```

```{r part1 q6}
## 6. Following up on the previous problem, now remove any countries of bean origins that have less than 10 chocolate bar reviews. Now, which top 3 countries have the highest ratings on average?

q6 <- chocolate %>%
  group_by(country_of_bean_origin) %>%
  summarize(
    mean_rating = mean (rating),
    review_date = n()
  )

q6_filtered <- q6 %>%
  filter(review_date >= 10)
  
top_country_rating <- q6_filtered %>%
  arrange(desc(mean_rating)) %>%
  top_n(3, wt = mean_rating)

print (top_country_rating)

```

```{r part1 q7}
## 7. For this last part, let’s explore the relationship between percent chocolate and ratings. Use the functions in dplyr, tidyr, and lubridate to perform the following steps to the chocolate dataset:


  

  
  
  
  
```

```{r part2 joining the datasets}
## 1.joining chocolate with gapminder and creating continent column
install.packages("gapminder")
library(gapminder)
gapminder_unfiltered

chocolate_renamed <- rename(chocolate, country = country_of_bean_origin)
head(chocolate_renamed)

Chocolate_continet <- left_join(chocolate_renamed, gapminder_unfiltered, by = "country") %>%
  select(-year, -lifeExp, -pop, -gdpPercap)

## keeping reviews with atleast 10
Chocolate_continet_10reviews <- Chocolate_continet %>% 
  group_by(country) %>%
  mutate(reviews_count = n()) %>%
  filter(reviews_count >=10)

##removing blend
Chocolate_continet_noblend <- filter(Chocolate_continet_10reviews, country != "Blend") 

is.na(Chocolate_continet_noblend$continent)

## violin plot
library(ggplot2)
ggplot(Chocolate_continet_noblend, aes(x=continent, y=rating)) + 
  geom_violin(fill="aquamarine") +
  labs(title= "Chocolate Ratings by Continent",
       x= "Continent",
       y = "Rating")








```


```{r part3}
#start with new chocolate tibble
chocolate <- readRDS(here("data", "chocolate.RDS"))
as_tibble(chocolate)

#load libraries
library(dplyr)
library(tidyr)
library(stringr)

#assign NA as 0

choc_3 <- chocolate %>%
  mutate(ingr_new = case_when(is.na(ingredients) ~ "0",
           TRUE ~ ingredients)
  )

# Create binary columns
choc_3 <- choc_3 %>%
  mutate(
    beans = ifelse(str_detect(ingr_new, "B"), 1, 0),
    sugar = ifelse(str_detect(ingr_new, "S"), 1, 0),
    cocoa_butter = ifelse(str_detect(ingr_new, "C"), 1, 0),
    vanilla = ifelse(str_detect(ingr_new, "V"), 1, 0),
    letchin = ifelse(str_detect(ingr_new, "L"), 1, 0),
    salt = ifelse(str_detect(ingr_new, "Sa"), 1, 0),
    char_cocoa = ifelse(str_detect(most_memorable_characteristics, "cocoa"), 1, 0),
    char_sweet = ifelse(str_detect(most_memorable_characteristics, "sweet"), 1, 0),
    char_nutty = ifelse(str_detect(most_memorable_characteristics, "nutty"), 1, 0),
    char_creamy = ifelse(str_detect(most_memorable_characteristics, "creamy"), 1, 0),
    char_roasty = ifelse(str_detect(most_memorable_characteristics, "roasty"), 1, 0),
    char_earthy = ifelse(str_detect(most_memorable_characteristics, "earthy"), 1, 0)
  )

#calculate mean values by year
mean_by_year <- choc_3 %>%
  group_by(review_date) %>%
  summarize(
    beans= mean(beans, na.rm = TRUE),
    sugar= mean(sugar, na.rm = TRUE),
    cocoa_butter= mean(cocoa_butter, na.rm = TRUE),
    vanilla= mean(vanilla, na.rm = TRUE),
    letchin= mean(letchin, na.rm = TRUE),
    salt= mean(salt, na.rm = TRUE),
    char_cocoa= mean(char_cocoa, na.rm = TRUE),
    char_sweet= mean(char_sweet, na.rm = TRUE),
    char_nutty= mean(char_nutty, na.rm = TRUE),
    char_roasty= mean(char_roasty, na.rm = TRUE),
    char_earthy= mean(char_earthy, na.rm = TRUE),
    char_creamy= mean(char_creamy, na.rm = TRUE))

#convert to from wide to long
long_format <- mean_by_year %>%
  pivot_longer(
    cols = c("beans":"char_creamy"),
    names_to = "feature",
    values_to = "mean_score"
  )
head(long_format, n=10)

```

```{r part4}
#Create a plot of long data
library(ggplot2)

ggplot(long_format, aes(x = review_date, y = mean_score)) +
  geom_point(color = "grey", size = 2) +  
  geom_smooth(method = "loess", color = "cyan") +
  facet_wrap(~ feature, scales = "free_y") +  
  labs(
    title = "Summary of Chocolate Review Over Time",
    subtitle = "Shows mean scores for various features in chocolate reviews from 2006 to 2021.",
    x = "Year of Review",
    y = "Mean Score",
    caption = "Created by Cathy Cooper"
  )  +  
  theme(
    strip.text = element_text(size = 10, face = "bold"),  # Facet labels
    axis.title = element_text(size = 12, face = "bold"),  # Axis titles
    axis.text = element_text(size = 10),  # Axis text
    plot.title = element_text(size = 14, face = "bold"),  # Plot title
    plot.subtitle = element_text(size = 12),  # Plot subtitle
    plot.caption = element_text(size = 10, face = "italic"),  # Caption
    panel.background = element_rect(fill = "lightgray")  # Background color
  )

```


```{r part5}
## 1.plotted rating in the y axis and  review date on the x axis using ggplot2.
plot1 <- ggplot(chocolate, aes( x = review_date, y = rating)) +
  geom_point()
print(plot1)

## 2. added a lowess smooth line by adding the geom_smooth function
plot2 <- ggplot(chocolate, aes( x = review_date, y = rating))+
  geom_point() +
  geom_smooth()
print(plot2)

## 3. used facets to compare between different company locations
plot3 <- ggplot(chocolate, aes( x = review_date, y = rating))+
  geom_point() +
  geom_smooth() +
  facet_grid(.~company_location)
print(plot3)

## 4. customizing the geometric points with different colors, sizes
plot4 <- ggplot(chocolate, aes( x = review_date, y = rating, color = "brown2" ))+
  geom_point( size = 2) +
  geom_smooth() +
  facet_grid(.~company_location)
print(plot4)

## 5. modifying the geom smooth by adding different line width, type and regression method
plot5 <- ggplot(chocolate, aes( x = review_date, y = rating, color = "brown2" ))+
  geom_point( size = 2) +
  geom_smooth( linewidth = 5, linetype = 5, method = "lm"  ) +
  facet_grid(.~company_location)
print(plot5)

## 6. modifying the labels and giving a chart title name 
plot6 <- ggplot(chocolate, aes( x = review_date, y = rating, color = "brown2" ))+
  geom_point( size = 2) +
  geom_smooth( linewidth = 5, linetype = 5, method = "lm"  ) +
  facet_grid(.~company_location)+
  labs(title = "Rating on different Review date", x = "Review date", y = "Rating" )
print(plot6)

## 7. setting a theme from the Themepark package
remotes::install_github("MatthewBJane/ThemePark")
library("ThemePark")
plot7 <- ggplot(chocolate, aes( x = review_date, y = rating, color = "brown2" ))+
  geom_point( size = 2) +
  geom_smooth( linewidth = 5, linetype = 5, method = "lm"  ) +
  facet_grid(.~company_location) +
  labs(title = "Rating on different Review date", x = "Review date", y = "Rating" ) +
  theme_gameofthrones()
print(plot7)

```

```{r part6}

```











